### ISSUE TITLE
Не отправляются сообщения в чат

### ISSUE THREAD

**Issue by sdfsdhgjkbmnmxc** [YuriSukhorukov/td-nane-client#1]
см. видео:
https://youtu.be/kYoo3Pyj0vI

**Comment by YuriSukhorukov** [comment]
Для отправки сообщений необходимо авторизоваться:
https://i.gyazo.com/2406133a07b27d0241436e16afa4c99c.mp4

**Comment by YuriSukhorukov** [comment]
> см. видео:
> https://youtu.be/kYoo3Pyj0vI



> см. видео:
> https://youtu.be/kYoo3Pyj0vI

Для отправки сообщений необходимо авторизоваться:
https://i.gyazo.com/2406133a07b27d0241436e16afa4c99c.mp4

**Comment by sdfsdhgjkbmnmxc** [comment]
А чего так сложно? :-(

**Comment by YuriSukhorukov** [comment]
Для отправки сообщений необходимо подключиться по ws передав имя пользователя. В таком случае логична автотризация. Сам способ авторизации имеет довольно распространенный вид для подобных приложений/сервисов. В техническом задании об этом сказано не было, поэтому я решил сделать так, как посчитал нужным.

**Comment by YuriSukhorukov** [comment]
> А чего так сложно? :-(

Для отправки сообщений необходимо подключиться по ws передав имя пользователя. В таком случае логична автотризация. Сам способ авторизации имеет довольно распространенный вид для подобных приложений/сервисов. В техническом задании об этом сказано не было, поэтому я решил сделать так, как посчитал нужным.
